import React, { ReactElement, useState } from 'react'
import Head from 'next/head'
import { useForm } from "react-hook-form"

import {default as VerifyLogo} from "../../media/logos/Verify.svg"
import {default as GraphLogo} from "../../media/logos/Graph.svg"
import {default as PaperUploadLogo} from "../../media/logos/PaperUpload.svg"

import styles from "../../styles/pages/profile.module.scss"
import Layout from '../../components/layouts/ServiceLayout/ServiceLayout'
import Input from 'src/components/UI/Input/Input'
import { Box, Flex, Radio, RadioGroup, Stack} from '@chakra-ui/react'
import rules from 'src/react-hook-form/rules'

import TileBlock from 'src/components/TileBlock/TileBlock'
import Button from 'src/components/UI/Button/Button'
import Helper, { mockProfile } from 'src/features/Navigation/Navigation'
import FormSegment from 'src/features/Profile/FormSegment'
import { useRouter } from 'next/router'

export default function UIPage() {
  const router = useRouter()
  const [activePage, setactivePage] = useState("Основные данные")
  const {control, watch} = useForm({
    mode: "all"
  })

  return (
    <>
      <Head>
        <title>Профиль | Молодежный бит</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <TileBlock style={{gridRow: "1", gridColumn: "1/3"}}>
          <div className={styles.userInfoBlock}>
            <div className={styles.img}>
              <img src="/Avatar.png" alt="" />
            </div>
            <div className={styles.info}>
              <Flex className={styles.name} gap=".3rem" alignItems="center">
                <h1>Незборецкий Кирилл</h1>
                <VerifyLogo/>
              </Flex>
              <Flex className={styles.idData} gap=".5rem" alignItems="center">
                <span>ID #343435</span>
                <span>nezbkir@gmail.com</span>
                <span>О себе</span>
              </Flex>
              <Flex className={styles.idData} gap=".3rem" alignItems="center">
                <Button onChange={() => console.log('clicked')}>
                  Заявка на грант
                </Button>
              </Flex>
            </div>
            <TileBlock style={{width: "100%", maxWidth: "250px"}}>
              <div className={styles.choosing}>
                <div className={styles.chItem}>
                  <span>Мои проекты</span>
                  <div className={styles.icon}>
                    <GraphLogo/>
                  </div>
                </div>
                <div className={styles.chItem} onClick={() => router.push("/profile/order/new")}>
                  <span>Заявки</span>
                  <div className={styles.icon}>
                    <PaperUploadLogo/>
                  </div>
                </div>
              </div>
            </TileBlock>
          </div>
        </TileBlock>
        <div className={styles.form}>
          <FormSegment title='Основные данные'>
            <Input
            rules={{
              ...rules.required,
            }}
            name='second_name'
            control={control}
            label='Фамилия'
            type='text'/>

            <Input
            rules={{
              ...rules.required,
              ...rules.validateDate
            }}
            name='date'
            control={control}
            label='Дата рождения'
            type='date'/>

            <Input
            rules={{
              ...rules.required,
            }}
            name='first_name'
            control={control}
            label='Имя'
            type='text'/>

            <Input
            name='phone'
            control={control}
            label='Номер телефона'
            type='phone'/>

            <Input
            name='middle_name'
            control={control}
            description="При наличии"
            label='Отчество'
            type='text'/>
            <Flex flexDir="column" gap="1rem">
              <span style={{fontSize: ".9rem"}}>Пол</span>
              <RadioGroup onChange={(value) => console.log(value)}>
                <Flex gap="1rem" direction='row'>
                  <Radio value='1' size='md'>
                    Женский
                  </Radio>
                  <Radio value='2' size='md'>
                    Мужской
                  </Radio>
                </Flex>
              </RadioGroup>
            </Flex>

          </FormSegment>

          <FormSegment title='Адрес'>
            <Input
            name='address'
            control={control}
            description="Начинайте вводить"
            label='Адрес'
            type='address'/>
          </FormSegment>

          <FormSegment title='Дополнительно'>
            <Input
            name='snils'
            control={control}
            description="Введите номер СНИЛС"
            label='СНИЛС'
            type='snils'/>
          </FormSegment>
        </div>
        <TileBlock style={{gridColumn: "1", gridRow: "2", height: "min-content"}}>
          <Helper onClick={(v) => setactivePage(v)} items={mockProfile.items} title={mockProfile.title} active={activePage}/>
        </TileBlock>
      </div>
    </>
  )
}

UIPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}