import React, { ReactElement, useState } from 'react'
import Head from 'next/head'
import { useForm } from "react-hook-form"

import styles from "../styles/pages/profile.module.scss"
import Layout from '../components/layouts/ServiceLayout/ServiceLayout'
import Input from 'src/components/UI/Input/Input'
import { Flex, Radio, RadioGroup, Stack } from '@chakra-ui/react'
import rules from 'src/react-hook-form/rules'

import TileBlock from 'src/features/TileBlock/TileBlock'

export default function UIPage() {
  const {control, watch} = useForm({
    mode: "all"
  })

  return (
    <>
      <Head>
        <title>Профиль | Молодежный бит</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <TileBlock>
          <h1></h1>
        </TileBlock>
        <Input
        name='name'
        control={control}
        description="Введите имя"
        label='Имя'
        type='text'/>
        
        <Input
        name='phone'
        control={control}
        description="Введите номер телефона"
        label='Номер телефона'
        type='phone'/>

        <Input
        rules={{
          ...rules.validateDate
        }}
        name='date'
        control={control}
        description="Введите дата рождения"
        label='Дата рождения'
        type='date'/>

        <Input
        rules={{
          ...rules.required,
          ...rules.validateAddress
        }}
        name='address'
        control={control}
        description="Начните вводить текст, поле заполнится автоматически"
        label='Адрес'
        type='address'/>

        <Input
        name='snils'
        control={control}
        description="Введите номер СНИЛС"
        label='СНИЛС'
        type='snils'/>

        <Input
        rules={{
        }}
        name='flat'
        control={control}
        description="Введите номер квартиры"
        label='Квартира'
        type='number'/>

        <RadioGroup onChange={(value) => console.log(value)}>
          <Flex gap="1rem" direction='row'>
            <Radio value='1' size='md'>
              Женский
            </Radio>
            <Radio value='2' size='md'>
              Мужской
            </Radio>
          </Flex>
        </RadioGroup>

      </div>
    </>
  )
}

UIPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}