import React, { ReactElement, useState } from 'react'
import Head from 'next/head'
import { useForm } from "react-hook-form"

import styles from "../styles/pages/ui.module.scss"
import Layout from '../../src/components/layouts/ServiceLayout/ServiceLayout'
import Input from 'src/components/UI/Input/Input'
import { Flex, Radio, RadioGroup, Stack } from '@chakra-ui/react'
import rules from 'utils/react-hook-form/rules'

export default function UIPage() {
  const {control} = useForm({
    mode: "all"
  })
  return (
    <>
      <Head>
        <title>Молодежный бит</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Input
        name='phone'
        control={control}
        description="Введите номер телефона"
        label='Номер телефона'
        type='phone'/>

        <Input
        rules={{
          ...rules.validateDate
        }}
        name='date'
        control={control}
        description="Введите номер телефона"
        label='Номер телефона'
        type='date'/>

        <RadioGroup onChange={(value) => console.log(value)}>
          <Flex gap="1rem" direction='row'>
            <Radio value='1' size='md'>
              Женский
            </Radio>
            <Radio value='2' size='md'>
              Мужской
            </Radio>
          </Flex>
        </RadioGroup>
      </div>
    </>
  )
}

UIPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}