import React, { ReactElement, useState } from 'react'
import Head from 'next/head'
import { useForm } from "react-hook-form"

import { FcDocument } from "react-icons/fc"

import styles from "../../../styles/pages/order.module.scss"
import Layout from '../../../components/layouts/ServiceLayout/ServiceLayout'

import { AnimatePresence } from 'framer-motion'
import FileInput from 'src/components/UI/FileInput/FileInput'
import TileBlock from 'src/components/TileBlock/TileBlock'
import Button from 'src/components/UI/Button/Button'

import { IoIosAdd } from "react-icons/io"
import { Flex } from '@chakra-ui/react'
import { useRouter } from 'next/router'

export default function OrderPage() {
  const [activePage, setactivePage] = useState("Общее")
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Гранты | Молодежный бит</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <TileBlock style={{width: "100%", maxWidth: "50rem", padding: "2rem"}}>
          <div className={styles.buttons}>
          <Button onClick={() => router.push("/profile/order/new")}>
            <Flex alignItems="center" gap=".5rem">
              <IoIosAdd fontSize="2rem"/>
              <span>Новая заявка (проект) на грант</span>
            </Flex>
          </Button>
          <Button >
            <Flex alignItems="center" gap=".5rem">
              <IoIosAdd fontSize="2rem"/>
              <span>Новая заявка (проект) на мероприятие</span>
            </Flex>
          </Button>
          </div>
          <h1 style={{fontSize: "2rem", marginTop:"2rem"}}>История заявок</h1>
          <h2 style={{fontSize: "1.1rem", opacity: 0.7}}>Пусто</h2>
        </TileBlock>
      </div>
    </>
  )
}

OrderPage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}